apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=0.5.1

# Change the value in params.env to yours.
configMapGenerator:
  - name: pipeline-cluster-scoped-install-config
    env: ../params.env
    behavior: merge